/* =====================================================
 * 「声生不息」互动答题题库
 * 题型：知识问答（text），中英双语
 * 知识点来源：
 *   - 知乎《古筝基础知识》(zhuanlan.zhihu.com/p/197246025)
 *   - 光明日报/北青网《笙：吹吸皆鸣的簧管乐器鼻祖》(zhuanlan.zhihu.com/p/664743554)
 *   - 主站「乐器资料库 / 经典曲目」板块
 * ===================================================== */
window.quizData = {
    zh:{
        praise:["妙哉，知音难觅！","金石丝竹，入耳如画！","此曲只应天上有！","一弦一柱，尽显风流！","妙手拨弦，韵动人心！"],
        text:[
            {id:"t01",
             q:"古筝按五声音阶定弦，这五个音依次叫作什么？",
             options:["宫、商、角、徵、羽","哆、来、咪、发、唆","宫、羽、角、商、徵","1、2、3、4、5"],answer:0,
             explain:"五声音阶为“宫、商、角、徵、羽”，对应简谱 1、2、3、5、6，没有 4（清角）和 7（变宫）。这正是古筝音色中中国韵味的源头。"},
            {id:"t02",
             q:"1957 年定型的现代标准古筝是几根弦？",
             options:["13 弦","16 弦","21 弦","25 弦"],answer:2,
             explain:"21 弦古筝于 1957 年定型，成为当代标准形制，极大拓展了音域与表现力。历史上古筝还经历过五弦、十二弦、十三弦、十五弦、十六弦等演变。"},
            {id:"t03",
             q:"古筝上可以左右移动、用来调节音高的部件叫作？",
             options:["岳山","雁柱（琴码）","义甲","弦枕"],answer:1,
             explain:"雁柱即琴码，一弦一码、可左右移动调音，是古筝区别于古琴的显著特征。义甲是戴在手指上的假指甲，岳山则是支撑琴弦的两端。"},
            {id:"t04",
             q:"古筝演奏讲究“右手取音，左手作韵”，左手的主要作用是？",
             options:["弹奏主旋律","按、滑、揉、颤","敲击面板","拨动琴码"],answer:1,
             explain:"左手在雁柱左侧通过按、滑、揉、颤等技法修饰音色、塑造韵味，还能按出 4、7 等变化音。这是筝乐艺术“以韵补声”的灵魂所在。"},
            {id:"t05",
             q:"下列哪一个不是中国传统的五大古筝流派？",
             options:["山东筝","潮州筝","客家筝","云南筝"],answer:3,
             explain:"五大传统流派为山东、河南、潮州、客家、浙江筝。山东筝铿锵明快，河南筝热烈高亢，潮州筝婉转细腻，客家筝古朴深沉，浙江筝清丽流畅。"},
            {id:"t06",
             q:"《高山流水》中“知音”的故事主人公是？",
             options:["伯牙与钟子期","孔子与老子","李白与杜甫","聂政与韩王"],answer:0,
             explain:"伯牙鼓琴、钟子期善听，能听懂琴声中的“高山”与“流水”。子期去世后伯牙绝弦，留下千古“知音”佳话。"},
            {id:"t07",
             q:"周代“八音”分类法中，笙属于哪一类？",
             options:["丝","匏","竹","金"],answer:1,
             explain:"八音为金、石、土、革、丝、木、匏、竹。笙用匏（葫芦）做笙斗，归为“匏”类；古筝的弦属“丝”类，故合称“丝竹”之乐。"},
            {id:"t08",
             q:"世界上最早使用自由簧的乐器是？",
             options:["口琴","手风琴","笙","风笛"],answer:2,
             explain:"笙采用自由簧发声，比欧洲的簧乐器早两千多年。十八世纪笙传入欧洲后，对手风琴、口琴、管风琴的发明都产生了启发。"},
            {id:"t09",
             q:"现代改良笙的笙斗（底座）通常使用什么材质？",
             options:["葫芦","木头","铜","竹子"],answer:2,
             explain:"笙斗的演变：先秦用天然葫芦（匏），唐代改为木斗，宋元以后多用铜斗。现代 21、24、36 簧加键笙普遍使用铜斗，并设有放水口。"},
            {id:"t10",
             q:"“滥竽充数”典故里，南郭先生混在哪种乐队中吹奏？",
             options:["竽（大型笙）","箫","笛","唢呐"],answer:0,
             explain:"竽是大型笙，与笙并称“笙竽”。故事出自《韩非子》，比喻没有真才实学的人混在行家中间充数，是笙文化在成语中的经典印记。"},
            {id:"t11",
             q:"我国第一首笙独奏曲《凤凰展翅》取材于？",
             options:["山西梆子音调","京剧西皮","昆曲水磨腔","广东音乐"],answer:0,
             explain:"《凤凰展翅》由胡天泉、董洪德创作，取材于山西梆子音调，是我国第一首笙独奏曲，充分展现了笙吹吸皆可发声、善奏和声的独特魅力。"},
            {id:"t12",
             q:"湖北曾侯乙墓出土的战国时期笙，距今约多少年？",
             options:["约 800 年","约 1200 年","约 2400 年","约 3500 年"],answer:2,
             explain:"1978 年曾侯乙墓出土五件匏笙，墓主下葬约在公元前 433 年，距今约 2400 余年。而甲骨文中的“龢”（和）字表明笙的起源可上溯至殷商，历史超三千年。"},
            {id:"t13",
             q:"笙在民族管弦乐团中主要担任什么角色？",
             options:["打击声部","和声融合声部","仅作独奏","低音弦乐"],answer:1,
             explain:"笙是中国传统乐器中少数原生具备和声能力的乐器，也是中国传统吹管乐器中唯一能演奏和声的乐器。其音色柔和丰满，能在乐团中调和、融合各声部音响。"},
            {id:"t14",
             q:"古筝被称为“东方钢琴”，还有一个响亮的别称是？",
             options:["众乐之王","乐器之王","弦乐之母","乐府之冠"],answer:0,
             explain:"古筝音域宽广、表现力极强，自古有“众乐之王”“东方钢琴”的美誉。它既能描绘高山流水的写意意境，也能演绎《战台风》般的磅礴气势。"},
            {id:"t15",
             q:"1965 年创作、表现码头工人与台风搏斗的古筝名曲是？",
             options:["《渔舟唱晚》","《战台风》","《寒鸦戏水》","《出水莲》"],answer:1,
             explain:"《战台风》由王昌元创作于 1965 年，描写码头工人与台风搏斗的场面。它以快速激烈的刮奏、扫弦技法，开创了古筝表现现代题材的先河。"},
            {id:"t16",
             q:"笙的三大核心部件不包括下列哪一项？",
             options:["笙簧","笙苗","笙斗","雁柱"],answer:3,
             explain:"笙由笙簧（自由簧片）、笙苗（竹管）、笙斗（底座气室）三大部件构成。雁柱是古筝的琴码，可别把两件乐器记混了。"},
            {id:"t17",
             q:"甲骨文中的“龢”字（即“和”）被学者认为是哪种乐器的象形文字？",
             options:["小笙","古筝","编钟","埙"],answer:0,
             explain:"笙的雏形可追溯至殷商时期，甲骨文中已有“龢”的象形文字，“龢”即小笙。这也是“笙是中国最古老簧管乐器”说法的重要依据。"},
            {id:"t18",
             q:"《诗经·小雅·鹿鸣》“我有嘉宾，鼓瑟吹笙”中提到的乐器是？",
             options:["瑟与笙","琴与箫","琵琶与笛","钟与磬"],answer:0,
             explain:"“鼓瑟吹笙”说明早在先秦，笙就已和瑟一起用于宴飨礼仪，是礼乐场合中不可或缺的乐器。"},
            {id:"t19",
             q:"传统笙的簧数一般为多少？",
             options:["九至十二簧","十三至十七簧","二十一至二十四簧","三十至三十六簧"],answer:1,
             explain:"传统笙的簧数多为十三至十七簧；20 世纪后出现了二十一簧、二十四簧、三十六簧乃至键盘笙等形制，显著扩展了音域。"},
            {id:"t20",
             q:"笙是中国传统吹管乐器中唯一能演奏什么音的乐器？",
             options:["和声","持续低音","花舌音","双吐音"],answer:0,
             explain:"笙的核心发声原理是“一簧一音”的自由簧结构——簧片独立振动、不受管体约束，因而可以同时奏出多个音符，具有和声与复调表现力。"},
            {id:"t21",
             q:"笙的簧片在古代用竹子制作，后来改用哪种材料？",
             options:["响铜","白银","乌木","兽骨"],answer:0,
             explain:"笙簧古代以竹制为主，后改用响铜制作。正是这种富有弹性的铜簧片，让笙具备了“吹吸皆鸣”的独特发声方式。"},
            {id:"t22",
             q:"约 8 世纪，笙东传至日本宫廷，演变为哪种乐器？",
             options:["日本笙（Shō）","尺八","三味线","龙笛"],answer:0,
             explain:"约 8 世纪，笙东传日本宫廷，发展为能奏十一和弦的日本笙（Shō）；韩国笙（Saenghwang）与东南亚的笙（Khaen）也都继承了自由簧核心特征。"},
            {id:"t23",
             q:"笙传入欧洲后，1810 年法国音乐家受其自由簧原理启发发明了哪种乐器？",
             options:["簧片风琴","钢琴","小提琴","萨克斯管"],answer:0,
             explain:"1740 年传教士将笙带到欧洲，此后口琴、手风琴、簧片风琴相继问世，均借鉴了笙的自由簧技术，推动了 19 世纪欧洲音乐的发展。"},
            {id:"t24",
             q:"古筝别名“秦筝”，是因为它在哪个时期流行于秦国（今陕西一带）？",
             options:["战国时期","汉代","唐代","宋代"],answer:0,
             explain:"早在公元前 5 至 3 世纪的战国时代，古筝就于秦国一带广泛流传，故得名“秦筝”，已有两千五百年以上的历史。"}
        ]
    },
    en:{
        praise:["Bravo, a kindred spirit!","Music to the ears!","Truly heavenly!","Perfect pitch!","An inspired choice!"],
        text:[
            {id:"t01",
             q:"Which scale is the Guzheng tuned in?",
             options:["Gong-Shang-Jue-Zhi-Yu (pentatonic)","Do-Re-Mi-Fa-Sol","Gong-Yu-Jue-Shang-Zhi","1-2-3-4-5"],answer:0,
             explain:"The pentatonic scale Gong, Shang, Jue, Zhi, Yu corresponds to 1, 2, 3, 5, 6 — without 4 or 7. This is the source of Guzheng's distinctive Chinese charm."},
            {id:"t02",
             q:"How many strings does the modern standard Guzheng (finalized in 1957) have?",
             options:["13","16","21","25"],answer:2,
             explain:"The 21-string Guzheng was standardized in 1957, greatly expanding the range. It evolved from 5-string, 12-string, 13-string, 15/16-string models."},
            {id:"t03",
             q:"What is the movable part on the Guzheng used to adjust pitch called?",
             options:["Yueshan (mountain)","Yanzhu (movable bridge)","Plectrum nails","String nut"],answer:1,
             explain:"Yanzhu is the movable bridge, one per string, for pitch adjustment — a key feature that distinguishes Guzheng from Guqin. Plectrum nails are worn on fingers; Yueshan supports both ends."},
            {id:"t04",
             q:"Guzheng playing emphasizes 'right hand makes sound, left hand makes charm'. What does the left hand mainly do?",
             options:["Plays the melody","Presses, slides and vibrates","Strikes the soundboard","Moves the bridges"],answer:1,
             explain:"The left hand creates semitones 4 and 7 and shapes the charm through pressing, sliding, kneading and vibrating techniques — the soul of Guzheng art."},
            {id:"t05",
             q:"Which is NOT one of the five traditional Guzheng schools?",
             options:["Shandong","Chaozhou","Hakka","Yunnan"],answer:3,
             explain:"The five traditional schools are Shandong, Henan, Chaozhou, Hakka and Zhejiang, each with its own distinct regional style and representative pieces."},
            {id:"t06",
             q:"Who are the protagonists of the 'bosom friend' story in 'High Mountain Running Water'?",
             options:["Bo Ya & Zhong Ziqi","Confucius & Laozi","Li Bai & Du Fu","Nie Zheng & King Han"],answer:0,
             explain:"Bo Ya played the Guqin while Zhong Ziqi heard the mountains and rivers in his music. After Ziqi's death, Bo Ya broke his strings — the timeless tale of a kindred spirit."},
            {id:"t07",
             q:"In the Zhou dynasty 'Eight Sounds' classification, which category does the Sheng belong to?",
             options:["Silk (Si)","Gourd (Pao)","Bamboo (Zhu)","Metal (Jin)"],answer:1,
             explain:"The Eight Sounds are metal, stone, earth, leather, silk, wood, gourd and bamboo. Sheng used a gourd wind chest, so it belongs to the Pao category; Guzheng strings are Silk."},
            {id:"t08",
             q:"Which instrument is the world's earliest free-reed instrument?",
             options:["Harmonica","Accordion","Sheng","Bagpipe"],answer:2,
             explain:"The Sheng sounds with free reeds, over 2,000 years earlier than European reed instruments. Introduced to Europe in the 18th century, it inspired the harmonica, accordion and organ."},
            {id:"t09",
             q:"What material is the wind chest of the modern improved Sheng usually made of?",
             options:["Gourd","Wood","Copper","Bamboo"],answer:2,
             explain:"The wind chest evolved from natural gourd (Pao) in pre-Qin times, to wood in the Tang dynasty, and copper since the Song/Yuan period. Modern 21-, 24-, 36-reed key-added Sheng uses copper with a water-drain hole."},
            {id:"t10",
             q:"In the idiom 'Yu Nang Chong Shu', which instrument did the impostor pretend to play?",
             options:["Yu (a large Sheng)","Xiao","Dizi","Suona"],answer:0,
             explain:"Yu is a large type of Sheng, together called 'Sheng-Yu'. The story from Han Feizi criticizes impostors who can't play but pretend to — a classic mark of Sheng culture in idioms."},
            {id:"t11",
             q:"The first Sheng solo piece 'Phoenix Spreads Its Wings' is based on?",
             options:["Shanxi Bangzi tunes","Peking opera Xipi","Kunqu melodies","Cantonese music"],answer:0,
             explain:"'Phoenix Spreads Its Wings' was composed by Hu Tianquan and Dong Hongde, based on Shanxi Bangzi tunes. It showcases the Sheng's unique blow-and-draw sound and harmony ability."},
            {id:"t12",
             q:"How old is the Warring-States Sheng unearthed from Marquis Yi of Zeng's tomb?",
             options:["About 800 years","About 1,200 years","About 2,400 years","About 3,500 years"],answer:2,
             explain:"Five gourd Sheng were unearthed in 1978 from the tomb buried around 433 BC, about 2,400 years ago. The oracle-bone character 'He' (龢) traces the Sheng's origin to the Shang dynasty, over 3,000 years."},
            {id:"t13",
             q:"What role does the Sheng usually play in a Chinese national orchestra?",
             options:["Percussion section","Harmony-blending section","Solo only","Bass strings"],answer:1,
             explain:"The Sheng is the only traditional Chinese wind instrument that can play harmony. Its soft, full timbre blends the orchestra's sections, acting as a sonic 'glue'."},
            {id:"t14",
             q:"Besides 'Oriental Piano', the Guzheng is also known as?",
             options:["King of Instruments","King of Music","Mother of Strings","Crown of the Music Bureau"],answer:0,
             explain:"With a wide range and strong expression, the Guzheng has been honored as the 'King of Instruments' and the 'Oriental Piano' since ancient times."},
            {id:"t15",
             q:"The 1965 Guzheng masterpiece depicting dock workers fighting a typhoon is?",
             options:["Fisherman's Song at Dusk","Fighting the Typhoon","Cold Crows Playing in Water","Lotus Rising from Water"],answer:1,
             explain:"'Fighting the Typhoon' was composed by Wang Changyuan in 1965. With fast sweeping and strumming techniques, it pioneered modern-themed Guzheng repertoire."},
            {id:"t16",
             q:"Which is NOT one of the three core parts of the Sheng?",
             options:["Reed","Bamboo pipe","Wind chest","Movable bridge"],answer:3,
             explain:"The Sheng consists of reeds (free-reed blades), bamboo pipes and the wind chest. The movable bridge belongs to the Guzheng — don't mix up the two instruments!"},
            {id:"t17",
             q:"The oracle-bone character '龢' (He, meaning harmony) is believed to be the pictograph of which instrument?",
             options:["A small Sheng","Guzheng","Bianzhong bells","Xun ocarina"],answer:0,
             explain:"The Sheng's prototype dates back to the Shang dynasty: the oracle-bone character '龢' (He) is a pictograph of a small Sheng. This is key evidence that the Sheng is China's oldest reed instrument."},
            {id:"t18",
             q:"In the Book of Songs ('I have honored guests, play the Se and blow the Sheng'), which instruments are mentioned?",
             options:["Se and Sheng","Qin and Xiao","Pipa and Dizi","Bells and chimes"],answer:0,
             explain:"'Blow the Sheng and play the Se' shows that as early as pre-Qin times the Sheng accompanied the Se at banquets and rituals — an indispensable court instrument."},
            {id:"t19",
             q:"How many reeds does a traditional Sheng usually have?",
             options:["9-12 reeds","13-17 reeds","21-24 reeds","30-36 reeds"],answer:1,
             explain:"Traditional Sheng usually have 13 to 17 reeds. Since the 20th century, 21-, 24-, 36-reed and even keyboard Sheng have appeared, greatly extending the range."},
            {id:"t20",
             q:"The Sheng is the only traditional Chinese wind instrument that can play what?",
             options:["Harmony","Sustained bass","Flutter-tonguing","Double-tonguing"],answer:0,
             explain:"The Sheng works on the 'one reed, one note' free-reed principle — reeds vibrate independently, so multiple notes can sound at once, giving it harmonic and polyphonic power."},
            {id:"t21",
             q:"The Sheng's reeds were originally made of bamboo; later they were made of what material?",
             options:["Resonant copper","Silver","Ebony","Animal bone"],answer:0,
             explain:"Sheng reeds were first bamboo, later changed to resonant copper. This springy copper reed is what gives the Sheng its unique 'sound on both blow and draw' ability."},
            {id:"t22",
             q:"Around the 8th century, the Sheng spread to the Japanese court and evolved into which instrument?",
             options:["Japanese Shō","Shakuhachi","Shamisen","Ryūteki"],answer:0,
             explain:"Around the 8th century the Sheng reached Japan and became the Shō, which can play eleven-note chords. Korea's Saenghwang and Southeast Asia's Khaen also kept the free-reed core."},
            {id:"t23",
             q:"After the Sheng reached Europe, what instrument did a French musician invent in 1810, inspired by its free-reed principle?",
             options:["Reed organ","Piano","Violin","Saxophone"],answer:0,
             explain:"Missionaries brought the Sheng to Europe in 1740; the reed organ (1810), harmonica and accordion all followed, borrowing the Sheng's free-reed technology and boosting 19th-century European music."},
            {id:"t24",
             q:"The Guzheng is also called 'Qin Zheng' because it was popular in the Qin state (today's Shaanxi) during which period?",
             options:["Warring States period","Han dynasty","Tang dynasty","Song dynasty"],answer:0,
             explain:"As early as the Warring States period (5th-3rd century BC), the instrument was widespread in the Qin state, hence the name 'Qin Zheng' — a history of over 2,500 years."}
        ]
    }
};

// 得分称号
window.quizRanks = [
    {min:0, zh:"初闻丝竹", en:"Novice Listener"},
    {min:4, zh:"乐府知音", en:"Kindred Spirit"},
    {min:6, zh:"丝竹妙手", en:"Music Scholar"},
    {min:8, zh:"传世乐师", en:"Master Musician"}
];
